### ISSUE TITLE
Frames not opening

### ISSUE THREAD

**Issue by stech11rt** [stech11845/cuddly-doodle#2]
the frames app on there does not open. assigned owner.

**Comment by stech11845** [comment]
It looks like a confliction of my code while reproducing.

**Comment by stech11845** [comment]
could you please make a pr?

**Comment by stech11845** [comment]
i could add collaborator access because you made pr

**Comment by stech11rt** [comment]
> i could add collaborator access because you made pr

THX

**Comment by stech11rt** [comment]
i did a commit
